name: Publish

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Install Ruby Dev
      run: sudo apt-get install ruby-dev

    - name: Install AsciiDoctor and Rouge
      run: sudo gem install asciidoctor rouge

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.62.0'

    - name: Build
      run: hugo

    # - name: Deploy
    #   uses: peaceiris/actions-gh-pages@v2
    #   env:
    #     ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
    #     PUBLISH_BRANCH: gh-pages
    #     PUBLISH_DIR: ./public

    - name: Prepare to push generated artifacts back to the repo
      run: |
        set -x
        ls -la
        echo "1---------"
        ls -la public
        git config --global user.email "shinglerjim@gmail.com"
        git config --global user.name "Jim Shingler"
        echo "1 status"
        git status
        cd ./public
        pwd
        echo "1git add"
        git add .
        echo "2---------"
        # echo ${{ secrets.ACTIONS_DEPLOY_KEY }}
        echo "2git status"
        git status
        echo "2git commit"
        git commit -m "Publish artifacts: `date`"
        echo "3git status"
        git status
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        EXTERNAL_REPOSITORY: jshingler/jshingler.github.io
        PUBLISH_BRANCH: master
        PUBLISH_DIR: ./public
              # - name: Push changes jshingler.github.io Master
              #   uses: ad-m/github-push-action@master
              #   with:
              #     github_token: ${{ secrets.GITHUB_TOKEN }}
              #     INPUT_GITHUB_TOKEN: ${{ secrets.blog-publish}}
              #     repository: jshingler/jshingler.github.io
              #     branch: master
              #     directory: public
              #   env:
              #     github_token: ${{ secrets.blog-publish}}
              #     INPUT_GITHUB_TOKEN: ${{ secrets.blog-publish}}

